import 'package:flutter/widgets.dart';

String tr(BuildContext context, String key) =>
    (Localizations.localeOf(context).languageCode == 'id' ? id : en)[key] ??
    en[key] ??
    key;
const en = {
  'invalidAsset': 'Check the asset fields and dates before saving.',
  'pastReminder': 'Choose a reminder time in the future.',
  'protect': 'Protect what you own.',
  'tagline': 'Everything You Own.\nProtected. Organized.',
  'intro':
      'Receipts, warranties and the little details that matter. One passport for every possession.',
  'google': 'Continue with Google',
  'local': 'Continue on this device',
  'localNote':
      'Your possessions are your data. Assets stay on this device. Signing in does not upload them.',
  'home': 'Overview',
  'assets': 'My assets',
  'reminders': 'Reminders',
  'settings': 'Settings',
  'hello': 'A little more peace of mind.',
  'dashboardIntro': 'Everything important, in its place.',
  'collection': 'YOUR COLLECTION',
  'assetCount': 'assets protected',
  'add': 'Add asset',
  'recent': 'Recently added',
  'all': 'All',
  'expiring': 'Warranty expiring',
  'returns': 'Returns due',
  'purchaseTotal': 'Purchase value',
  'empty': 'Your first passport starts here.',
  'emptyBody':
      'Add something you value. Keep its details close, whenever you need them.',
  'search': 'Search name, brand, serial or store',
  'noResults': 'No matching assets.',
  'save': 'Save passport',
  'name': 'Asset name',
  'brand': 'Brand',
  'model': 'Model',
  'serial': 'Serial number / IMEI / VIN',
  'vendor': 'Store / vendor',
  'price': 'Purchase price',
  'currency': 'Currency',
  'category': 'Category',
  'purchaseDate': 'Purchase date',
  'warrantyEnd': 'Warranty ends',
  'returnEnd': 'Return deadline',
  'notes': 'Notes',
  'photo': 'Add a photo',
  'edit': 'Edit',
  'delete': 'Delete asset',
  'deleteBody':
      'Remove this asset from your collection and cancel its reminders? It remains in the local history and backups.',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'overview': 'Overview',
  'documents': 'Documents',
  'timeline': 'Timeline',
  'attach': 'Attach document',
  'noDocuments': 'Keep a receipt, warranty, manual or PDF here.',
  'newReminder': 'Add reminder',
  'title': 'Reminder title',
  'due': 'Due date',
  'noReminders': 'No upcoming reminders. Add one from an asset passport.',
  'privacy': 'Private by default',
  'privacyBody':
      'Assets and documents are stored in this app on this device. Google sign-in sends authentication information to Google/Firebase. There is no automatic cloud backup or asset upload. Local files rely on Android device protection; use a screen lock. Exported backups are password-encrypted.',
  'account': 'Account',
  'signedOut': 'Local device vault',
  'signOut': 'Sign out',
  'language': 'Language',
  'backup': 'Encrypted backup',
  'export': 'Export backup',
  'import': 'Restore backup',
  'backupBody':
      'Includes assets, documents, photos and reminders. Keep your password safe: it cannot be recovered.',
  'password': 'Backup password (12+ characters)',
  'replaceBody':
      'Restore replaces the current local inventory. Export a backup first if you want to keep it.',
  'success': 'Saved successfully.',
  'restored':
      'Backup restored. Check notification permission to receive reminders.',
  'error':
      'Something went wrong. Your saved data is still on this device. Please try again.',
  'limit':
      'The free plan supports 10 assets. Paid plans are not available in this release.',
  'fileSize': 'Choose a file smaller than 10 MB.',
  'fileType': 'Use a JPG, PNG, PDF or plain text file.',
  'backupSize': 'This backup is too large (40 MB of files maximum).',
  'backupInvalid':
      'Unable to restore. Check your password and backup file. Your existing inventory was not replaced.',
  'passwordShort': 'Use a password of at least 12 characters.',
  'firebaseMissing':
      'Google sign-in is not configured yet. Follow docs/FIREBASE.md, or continue on this device.',
  'firebaseFailed':
      'Firebase could not start. Check app configuration and try again.',
  'loginFailed':
      'Google sign-in could not finish. Check the Firebase configuration and try again.',
  'offline': 'You appear to be offline. Your local assets remain available.',
  'apiMissing': 'Configure an HTTPS API_BASE_URL to check your server session.',
  'apiFailed': 'The server could not verify your session. Please try again.',
  'verify': 'Verify server session',
  'verified': 'Your server session is verified.',
  'required': 'This field is required.',
  'invalidPrice': 'Enter a valid non-negative amount.',
  'invalidDate': 'A deadline cannot be before the purchase date.',
  'unset': 'Not set',
  'created': 'Passport created',
  'updated': 'Passport updated',
  'document': 'Document attached',
  'reminder': 'Reminder added',
  'deleted': 'Passport deleted',
  'Active': 'Active',
  'Unknown': 'Unknown',
  'Expired': 'Expired',
  'Expiring soon': 'Expiring soon',
  'notificationDenied':
      'Notification permission is off. The reminder is saved in the app.',
  'notificationFailed':
      'The reminder is saved, but a notification could not be scheduled. Try again from Settings.',
  'retryNotifications': 'Enable / reschedule notifications',
  'free': 'FREE · 10 assets',
  'notCloud': 'This device only · No cloud sync',
  'sort': 'Sort',
  'newest': 'Newest',
  'highest': 'Highest price',
  'clear': 'Clear',
  'photoMissing': 'Photo unavailable',
  'openFailed': 'No compatible app could open this document.',
  'backupCancelled': 'Export cancelled.',
  'camera': 'Camera',
  'gallery': 'Photo library',
  'today': 'Due today',
  'days': 'days remaining',
};
const id = {
  'invalidAsset': 'Periksa kolom aset dan tanggal sebelum menyimpan.',
  'pastReminder': 'Pilih waktu pengingat di masa depan.',
  'protect': 'Lindungi barang berharga Anda.',
  'tagline': 'Semua Milik Anda.\nTerlindungi. Teratur.',
  'intro':
      'Nota, garansi, dan detail penting. Satu paspor untuk setiap barang berharga.',
  'google': 'Lanjutkan dengan Google',
  'local': 'Lanjutkan di perangkat ini',
  'localNote':
      'Barang Anda, data Anda. Aset disimpan di perangkat ini. Login tidak mengunggahnya.',
  'home': 'Ringkasan',
  'assets': 'Aset saya',
  'reminders': 'Pengingat',
  'settings': 'Pengaturan',
  'hello': 'Lebih teratur, lebih tenang.',
  'dashboardIntro': 'Semua yang penting, di tempatnya.',
  'collection': 'KOLEKSI ANDA',
  'assetCount': 'aset tersimpan',
  'add': 'Tambah aset',
  'recent': 'Baru ditambahkan',
  'all': 'Semua',
  'expiring': 'Garansi segera habis',
  'returns': 'Batas retur',
  'purchaseTotal': 'Nilai pembelian',
  'empty': 'Paspor pertama Anda dimulai di sini.',
  'emptyBody':
      'Tambahkan barang berharga dan simpan detailnya agar selalu mudah ditemukan.',
  'search': 'Cari nama, merek, serial, atau toko',
  'noResults': 'Tidak ada aset yang cocok.',
  'save': 'Simpan paspor',
  'name': 'Nama aset',
  'brand': 'Merek',
  'model': 'Model',
  'serial': 'Nomor seri / IMEI / VIN',
  'vendor': 'Toko / penjual',
  'price': 'Harga pembelian',
  'currency': 'Mata uang',
  'category': 'Kategori',
  'purchaseDate': 'Tanggal pembelian',
  'warrantyEnd': 'Garansi berakhir',
  'returnEnd': 'Batas retur',
  'notes': 'Catatan',
  'photo': 'Tambah foto',
  'edit': 'Ubah',
  'delete': 'Hapus aset',
  'deleteBody':
      'Hapus aset dari koleksi dan batalkan pengingatnya? Riwayat lokal dan backup tetap menyimpannya.',
  'cancel': 'Batal',
  'confirm': 'Konfirmasi',
  'overview': 'Ringkasan',
  'documents': 'Dokumen',
  'timeline': 'Riwayat',
  'attach': 'Lampirkan dokumen',
  'noDocuments': 'Simpan nota, garansi, manual, atau PDF di sini.',
  'newReminder': 'Tambah pengingat',
  'title': 'Judul pengingat',
  'due': 'Tanggal pengingat',
  'noReminders': 'Belum ada pengingat. Tambahkan dari halaman paspor aset.',
  'privacy': 'Privasi sejak awal',
  'privacyBody':
      'Aset dan dokumen tersimpan di aplikasi pada perangkat ini. Login Google mengirim informasi autentikasi ke Google/Firebase. Tidak ada backup cloud atau unggahan aset otomatis. File lokal mengandalkan perlindungan Android; gunakan kunci layar. Backup ekspor dienkripsi dengan password.',
  'account': 'Akun',
  'signedOut': 'Penyimpanan lokal perangkat',
  'signOut': 'Keluar',
  'language': 'Bahasa',
  'backup': 'Backup terenkripsi',
  'export': 'Ekspor backup',
  'import': 'Pulihkan backup',
  'backupBody':
      'Mencakup aset, dokumen, foto, dan pengingat. Simpan password Anda: password tidak dapat dipulihkan.',
  'password': 'Password backup (minimal 12 karakter)',
  'replaceBody':
      'Pemulihan mengganti inventaris lokal saat ini. Ekspor backup terlebih dahulu untuk menyimpannya.',
  'success': 'Berhasil disimpan.',
  'restored':
      'Backup dipulihkan. Periksa izin notifikasi untuk menerima pengingat.',
  'error':
      'Terjadi masalah. Data yang tersimpan tetap ada di perangkat ini. Silakan coba lagi.',
  'limit':
      'Paket gratis mendukung 10 aset. Paket berbayar belum tersedia di rilis ini.',
  'fileSize': 'Pilih file berukuran di bawah 10 MB.',
  'fileType': 'Gunakan JPG, PNG, PDF, atau teks biasa.',
  'backupSize': 'Backup terlalu besar (maksimal 40 MB file).',
  'backupInvalid':
      'Gagal memulihkan. Periksa password dan file backup. Inventaris lama tidak diganti.',
  'passwordShort': 'Gunakan password minimal 12 karakter.',
  'firebaseMissing':
      'Login Google belum dikonfigurasi. Ikuti docs/FIREBASE.md atau lanjutkan di perangkat ini.',
  'firebaseFailed': 'Firebase gagal dimulai. Periksa konfigurasi aplikasi.',
  'loginFailed':
      'Login Google gagal. Periksa konfigurasi Firebase dan coba lagi.',
  'offline': 'Anda tampaknya offline. Aset lokal tetap dapat diakses.',
  'apiMissing': 'Atur API_BASE_URL HTTPS untuk memeriksa sesi server.',
  'apiFailed': 'Server gagal memverifikasi sesi. Silakan coba lagi.',
  'verify': 'Verifikasi sesi server',
  'verified': 'Sesi server berhasil diverifikasi.',
  'required': 'Kolom ini wajib diisi.',
  'invalidPrice': 'Masukkan nominal valid dan tidak negatif.',
  'invalidDate': 'Batas waktu tidak boleh sebelum tanggal pembelian.',
  'unset': 'Belum diisi',
  'created': 'Paspor dibuat',
  'updated': 'Paspor diperbarui',
  'document': 'Dokumen dilampirkan',
  'reminder': 'Pengingat ditambahkan',
  'deleted': 'Paspor dihapus',
  'Active': 'Aktif',
  'Unknown': 'Belum diketahui',
  'Expired': 'Berakhir',
  'Expiring soon': 'Segera berakhir',
  'notificationDenied':
      'Izin notifikasi belum aktif. Pengingat tersimpan di aplikasi.',
  'notificationFailed':
      'Pengingat tersimpan, tetapi notifikasi gagal dijadwalkan. Coba lagi melalui Pengaturan.',
  'retryNotifications': 'Aktifkan / jadwalkan ulang notifikasi',
  'free': 'GRATIS · 10 aset',
  'notCloud': 'Hanya perangkat ini · Tanpa sinkronisasi',
  'sort': 'Urutkan',
  'newest': 'Terbaru',
  'highest': 'Harga tertinggi',
  'clear': 'Kosongkan',
  'photoMissing': 'Foto tidak tersedia',
  'openFailed': 'Tidak ada aplikasi yang dapat membuka dokumen ini.',
  'backupCancelled': 'Ekspor dibatalkan.',
  'camera': 'Kamera',
  'gallery': 'Galeri foto',
  'today': 'Jatuh tempo hari ini',
  'days': 'hari tersisa',
  'Electronics': 'Elektronik',
  'Appliances': 'Peralatan rumah',
  'Furniture': 'Furnitur',
  'Vehicles': 'Kendaraan',
  'Photography': 'Fotografi',
  'Jewelry': 'Perhiasan',
  'Tools': 'Perkakas',
  'Sports': 'Olahraga',
  'Other': 'Lainnya',
};
